import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import { Box } from "@mui/material";
import styles from "@/styles/Home.module.css";
import Navbar from "@/components/Navbar";
import Hero from "@/components/Hero";
import AboutUs from "@/components/Aboutus";
import OurDomains from "@/components/Domains";
import Domain from "@/components/Knowdomains";
import CustomForm from "@/components/Contactus";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Machine Learning Centre of Excellence</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Box display="flex" flexDirection="column" width="100%"  m={0}>
     <Navbar />
     <Hero />
     <AboutUs />
     <OurDomains />
     <Domain />
     <CustomForm />
     <Footer />
     </Box>
    </>
  );
}
